package flavor

// harbWarnAges is the speaker's own copy: the cry, the chart, the headline, the
// dispatch, the memo, the message from nine years out. Thirteen lines per age,
// spread over the tiers so each tier hears the speaker at least four times.
//
// These are the lines most likely to be quoted back at the player, so they are
// the most era-bound in the catalog. A crier says oyez; a newsboy says read all
// about it; the chain email wants forwarding. From the Industrial Age the
// medium has the odds and says so, without ever printing them.
var harbWarnAges = []ageSet{
	{ages("primitive_age"), []skel{
		{Text: "He sniffed the wind, spat, and said the wind was only wind", Kinds: tNone, Reg: rWry, Topic: "weather"},
		{Text: "The ashes said nothing", Kinds: tNone, Reg: rJoke, Topic: "omen"},
		{Text: "All he said was “Nothing comes,” and he went on eating", Kinds: tNone, Reg: rPlain, Form: fOverheard, Topic: "food"},
		{Text: "He looked at the sky and at the herd and at the children, grunted, and left before dark", Kinds: tNoneLow, Reg: rPlain, Topic: "stranger"},
		{Text: "Over and over he said “small teeth,” and nobody knew what small teeth meant", Kinds: tLow, Reg: rWry, Form: fOverheard, Topic: "omen"},
		{Text: "He tied a black feather over the entrance of the biggest hut and would not say why", Kinds: tLow, Reg: rPlain, Topic: "omen"},
		{Text: "He drew a wolf in the ash, then rubbed it half out", Kinds: tLowMed, Reg: rPlain, Topic: "animal"},
		{Text: "Pressing his ear to the ground, he said “It will be hungry”", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "ground"},
		{Text: "He went from hut to hut smearing ash on the doorposts of every hut that had a child in it, and when he had finished he went round again to check, and the mothers stood in the doorways and let him", Kinds: tMed, Reg: rPlain, Topic: "family"},
		{Text: "He howled and the dogs answered", Kinds: tMedHigh, Reg: rPlain, Topic: "noise"},
		{Text: "The wild man screamed “Fire from above, fire from above” and tore at his hair until it came out in his hands", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "omen"},
		{Text: "He would not sleep under any shelter and ran off into the dark still shouting", Kinds: tHigh, Reg: rPlain, Topic: "sleep"},
		{Text: "He broke his own spear across his knee and threw the pieces into the fire", Kinds: tHigh, Reg: rPlain, Topic: "weapon"},
	}},
	{ages("stone_age"), []skel{
		{Text: "The hermit sat a whole day on the high rock and came down to say the sky was empty", Kinds: tNone, Reg: rPlain, Topic: "weather"},
		{Text: "The hermit shrugged", Kinds: tNone, Reg: rPlain, Topic: "stranger"},
		{Text: "His whole answer was “Nothing,” and he went back up to his cave", Kinds: tNone, Reg: rPlain, Form: fOverheard, Topic: "stranger"},
		{Text: "He counted the stars over the ridge and found them all present", Kinds: tNoneLow, Reg: rWry, Topic: "omen"},
		{Text: "He said the winter would be long, and that the long winters were the ones people remembered", Kinds: tLow, Reg: rPlain, Topic: "weather"},
		{Text: "He told them to watch the water, which could have meant anything", Kinds: tLow, Reg: rWry, Form: fOverheard, Topic: "message"},
		{Text: "He left three flat rocks stacked at the cave mouth and would not explain them", Kinds: tLowMed, Reg: rPlain, Topic: "omen"},
		{Text: "Pointing north with his whole arm, he said “The cold is walking”", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "weather"},
		{Text: "He told the women to dry every scrap of meat before the next moon", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "food"},
		{Text: "He avoided the children's eyes", Kinds: tMedHigh, Reg: rPlain, Topic: "family"},
		{Text: "The mountain would shake the caves loose, the hermit said, and he would not go back up to his own", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "ground"},
		{Text: "He painted his face red, which the oldest woman said meant the worst thing it could mean", Kinds: tHigh, Reg: rPlain, Topic: "omen"},
		{Text: "He sat down in the middle of the camp and would not get up for food or for the rain, and by the third day the children had stopped being frightened of him and were bringing him things", Kinds: tHigh, Reg: rPlain, Topic: "people"},
	}},
	{ages("bronze_age"), []skel{
		{Text: "The liver was clean, the birds flew right, and she wanted paying anyway", Kinds: tNone, Reg: rJoke, Form: fComplaint, Topic: "money"},
		{Text: "The knucklebones came up plain", Kinds: tNone, Reg: rPlain, Topic: "omen"},
		{Text: "She read the sparrows for most of the afternoon, and the knucklebones after that, and a goat's liver after that, and could make nothing ominous of any of them, and in the end she asked for her fee and her mule", Kinds: tNone, Reg: rPlain, Topic: "animal"},
		{Text: "The gods were bored with them, she said, which was taken as good news", Kinds: tNoneLow, Reg: rWry, Form: fOverheard, Topic: "religion"},
		{Text: "The liver had a small spot on it, low down, which she said was a bad harvest or a bad marriage", Kinds: tLow, Reg: rWry, Topic: "omen"},
		{Text: "One sparrow in seven flew left", Kinds: tLow, Reg: rPlain, Form: fLedger, Topic: "animal"},
		{Text: "She would not say what the knucklebones meant, and charged extra for not saying", Kinds: tLowMed, Reg: rJoke, Topic: "money"},
		{Text: "The liver was spotted all over, and she held it up so everyone could see", Kinds: tMed, Reg: rPlain, Topic: "omen"},
		{Text: "In the voice they use for this she said “The bronze will crack and the grain will rot”", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "food"},
		{Text: "The sparrows stayed caged", Kinds: tMedHigh, Reg: rPlain, Topic: "animal"},
		{Text: "She cut open the goat, looked once, and would not touch it again", Kinds: tHigh, Reg: rPlain, Topic: "animal"},
		{Text: "The river god was angry and the sky god angrier, she said, and she wept, and asked for no fee", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "religion"},
		{Text: "Every bird in her cage died in the night, and she carried them to the temple in the morning to be seen", Kinds: tHigh, Reg: rPlain, Topic: "omen"},
	}},
	{ages("iron_age"), []skel{
		{Text: "His prophecy began “Thus says the voice in the desert” and then stopped, because there was nothing to follow it, and he looked annoyed about it", Kinds: tNone, Reg: rJoke, Form: fOverheard, Topic: "message"},
		{Text: "He had come to curse the city and could find nothing in it worth the trouble", Kinds: tNone, Reg: rWry, Topic: "town"},
		{Text: "He ate figs by the well", Kinds: tNone, Reg: rPlain, Topic: "food"},
		{Text: "He preached against gluttony, mainly", Kinds: tNoneLow, Reg: rWry, Topic: "religion"},
		{Text: "To the whole market he said “A dry year is coming, and you have earned it”", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "weather"},
		{Text: "He cursed only the tax collectors", Kinds: tLow, Reg: rWry, Topic: "money"},
		{Text: "He wrote something in the dust by the well and walked away before anyone could read it", Kinds: tLowMed, Reg: rPlain, Topic: "message"},
		{Text: "Woe to the city of fat men, he cried, and the fat men went indoors", Kinds: tMed, Reg: rWry, Form: fOverheard, Topic: "town"},
		{Text: "The day he named was soon", Kinds: tMed, Reg: rPlain, Topic: "time"},
		{Text: "His voice broke halfway and he had to start the curse again", Kinds: tMedHigh, Reg: rPlain, Topic: "noise"},
		{Text: "Over and over, until his voice was gone, he cried “The sky will be brass and the earth iron, and the rain will be dust”", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "weather"},
		{Text: "He tore his cloak from neck to hem in front of the whole market and stood there in what was left of it, and the traders who had laughed at him the day before packed their stalls and went home without being told", Kinds: tHigh, Reg: rPlain, Topic: "people"},
		{Text: "He lay face down in the square and would not stop praying", Kinds: tHigh, Reg: rPlain, Topic: "religion"},
	}},
	{ages("classical_age"), []skel{
		{Text: "The priests brought back a riddle about a goat and a fig tree, and after much discussion it meant nothing", Kinds: tNone, Reg: rJoke, Topic: "message"},
		{Text: "She said the gods were looking elsewhere this year", Kinds: tNone, Reg: rPlain, Form: fOverheard, Topic: "religion"},
		{Text: "Her answer was a single word, and the priests agreed it was a pleasant one", Kinds: tNone, Reg: rWry, Topic: "message"},
		{Text: "Her answer was so vague that three different philosophers wrote books about it, each proving it meant something different, and by the time the third book was finished the season in question had come and gone without incident", Kinds: tNoneLow, Reg: rWry, Topic: "paper"},
		{Text: "Her answer was “A shadow falls on the olive,” and the olive growers took it personally", Kinds: tLow, Reg: rWry, Form: fOverheard, Topic: "food"},
		{Text: "She spoke of a small grief, and the priests argued about how small", Kinds: tLow, Reg: rPlain, Topic: "argument"},
		{Text: "The smoke over the cleft rock was grey, neither white nor black", Kinds: tLowMed, Reg: rPlain, Topic: "omen"},
		{Text: "Her words were “When the owl sings at noon, the walls will learn to weep,” and the priests wrote them on a tablet and sent them by fast horse", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "The priests who brought the answer had been told to repeat it word for word, and they did, and they would add nothing of their own", Kinds: tMed, Reg: rPlain, Topic: "religion"},
		{Text: "She spoke without being asked", Kinds: tMedHigh, Reg: rPlain, Topic: "omen"},
		{Text: "She said “The city will be a field and the field will be ash,” and then would not speak again for a month", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "town"},
		{Text: "The priests came back in mourning", Kinds: tHigh, Reg: rPlain, Topic: "religion"},
		{Text: "Her answer was written in a hand so shaken that it took the scribes a day to read it", Kinds: tHigh, Reg: rPlain, Topic: "paper"},
	}},
	{ages("medieval_age"), []skel{
		{Text: "The crier's cry was “Oyez, oyez, all is well, and the price of salt is down a farthing,” and then he moved on to the lost cow", Kinds: tNone, Reg: rJoke, Form: fNotice, Topic: "trade"},
		{Text: "He rang the bell to say there was nothing to ring the bell about", Kinds: tNone, Reg: rWry, Topic: "noise"},
		{Text: "The crier cried the fair, the tolls and the lost cow, and nothing else", Kinds: tNone, Reg: rPlain, Form: fNotice, Topic: "trade"},
		{Text: "He read the doom off his paper in the voice he keeps for market tolls", Kinds: tNoneLow, Reg: rWry, Topic: "paper"},
		{Text: "At every corner he cried “Be it known that there is talk of a bad summer, and the lord advises prudence”", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "weather"},
		{Text: "He cried the warning between the lost pig and the new toll on the bridge", Kinds: tLow, Reg: rWry, Form: fNotice, Topic: "animal"},
		{Text: "The bell rang long", Kinds: tLowMed, Reg: rPlain, Topic: "noise"},
		{Text: "Hear ye, he cried, the lord bids every household lay in grain and keep its doors barred after dark", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "authority"},
		{Text: "He cried it in the market, at the church door, at the ford and at the mill, and his voice got worse at each, so that by the mill the miller had to come out and ask him to say it again", Kinds: tMed, Reg: rPlain, Topic: "town"},
		{Text: "The crier's hand shook on the bell rope", Kinds: tMedHigh, Reg: rPlain, Topic: "people"},
		{Text: "God save us all, he cried, which is not in the usual form", Kinds: tHigh, Reg: rWry, Form: fOverheard, Topic: "religion"},
		{Text: "He rang the bell until it cracked and went on shouting after it had stopped", Kinds: tHigh, Reg: rPlain, Topic: "noise"},
		{Text: "His last cry was “The end is on the road and it will be here by the feast,” and then he sat down on the church steps and would cry nothing else", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "time"},
	}},
	{ages("renaissance_age"), []skel{
		{Text: "The charts were clear, the conjunctions were kind, and his fee was as large as ever", Kinds: tNone, Reg: rJoke, Topic: "money"},
		{Text: "Jupiter was in a good house and the prince went hunting", Kinds: tNone, Reg: rPlain, Topic: "omen"},
		{Text: "He found no bad aspect anywhere in the heavens and seemed personally slighted", Kinds: tNone, Reg: rWry, Topic: "omen"},
		{Text: "Saturn was sulking, he said, but no more than usual", Kinds: tNoneLow, Reg: rWry, Form: fOverheard, Topic: "omen"},
		{Text: "Mars was rising in the house of grain, which he said meant a lean autumn", Kinds: tLow, Reg: rPlain, Topic: "food"},
		{Text: "He advised the prince to postpone his wedding, and would not say why in front of the bride", Kinds: tLow, Reg: rJoke, Topic: "authority"},
		{Text: "He redrew the chart by candlelight and asked for a second opinion from himself", Kinds: tLowMed, Reg: rJoke, Topic: "paper"},
		{Text: "Reading aloud, he announced “Saturn and Mars stand together in the house of death,” and the court stopped eating", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "omen"},
		{Text: "He sealed his chart with black wax and sent it to the prince unopened", Kinds: tMed, Reg: rPlain, Topic: "paper"},
		{Text: "He asked for his wages early", Kinds: tMedHigh, Reg: rWry, Form: fComplaint, Topic: "money"},
		{Text: "A great conjunction, he announced, such as has not been seen in three hundred years, and he dropped his pointer", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "omen"},
		{Text: "He burned his own horoscope", Kinds: tHigh, Reg: rPlain, Topic: "paper"},
		{Text: "He was seen that night by the kitchen boys packing his instruments into a travelling chest, the astrolabe wrapped in his second-best cloak, and the kitchen boys told the cook, and by morning the whole palace knew", Kinds: tHigh, Reg: rPlain, Topic: "kit"},
	}},
	{ages("colonial_age"), []skel{
		{Text: "Her new pamphlet was titled A Calm Assessment and sold three copies", Kinds: tNone, Reg: rJoke, Form: fLedger, Topic: "paper"},
		{Text: "She had nothing dreadful to print, and printed a recipe for pickled herring instead", Kinds: tNone, Reg: rWry, Topic: "food"},
		{Text: "The press stood idle all week", Kinds: tNone, Reg: rPlain, Topic: "machine"},
		{Text: "Her pamphlet warned mostly against the price of tea", Kinds: tNoneLow, Reg: rWry, Topic: "trade"},
		{Text: "A Sober Word Concerning the Coming Season, price one penny, was being read in every coffee house", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "paper"},
		{Text: "She printed a warning in small type at the bottom of the shipping notices, between a sale of indentures and a reward for a runaway horse, where the only people likely to read it were the people who read everything", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "trade"},
		{Text: "Black borders this week", Kinds: tLowMed, Reg: rPlain, Topic: "paper"},
		{Text: "Her new pamphlet was titled A True and Terrible Warning to the Inhabitants of This Colony, and ran to forty pages", Kinds: tMed, Reg: rWry, Form: fNotice, Topic: "paper"},
		{Text: "The printer ran off two thousand copies overnight and ran out of paper", Kinds: tMed, Reg: rPlain, Form: fLedger, Topic: "count"},
		{Text: "Her hands were black to the wrist from setting type all night", Kinds: tMedHigh, Reg: rPlain, Topic: "work"},
		{Text: "THE JUDGEMENT IS AT HAND, the pamphlet said across its whole front page, in the largest type the colony possessed", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "message"},
		{Text: "Free pamphlets, for once", Kinds: tHigh, Reg: rPlain, Topic: "money"},
		{Text: "The governor had her press seized, and the pamphlet went round in handwritten copies instead, faster than it had in print", Kinds: tHigh, Reg: rPlain, Topic: "authority"},
	}},
	{ages("industrial_age"), []skel{
		{Text: "The newsboy called it a slow news day and sold papers about a prize marrow", Kinds: tNone, Reg: rJoke, Form: fOverheard, Topic: "paper"},
		{Text: "The late edition put the odds on page nine, under the shipping news", Kinds: tNone, Reg: rPlain, Topic: "paper"},
		{Text: "All he had to shout was nothing doing, nothing doing, and he shouted it without much hope", Kinds: tNone, Reg: rWry, Form: fOverheard, Topic: "noise"},
		{Text: "The headline was about the mayor's gout", Kinds: tNoneLow, Reg: rWry, Topic: "paper"},
		{Text: "SMALL CHANCE OF CALAMITY, EXPERTS SAY, the boy shouted, and he sold more papers than he expected", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "paper"},
		{Text: "The odds were printed in a box on page three, next to an advertisement for liver pills", Kinds: tLow, Reg: rWry, Topic: "paper"},
		{Text: "The odds moved to page one", Kinds: tLowMed, Reg: rPlain, Topic: "paper"},
		{Text: "ODDS SHORTEN ON DISASTER, he shouted, read all about it, and people stopped in the road to buy", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "noise"},
		{Text: "The morning paper printed the odds in a black-bordered box on the front page", Kinds: tMed, Reg: rPlain, Topic: "paper"},
		{Text: "The boy was sold out by ten and sent back to the yard for more", Kinds: tMedHigh, Reg: rPlain, Form: fLedger, Topic: "count"},
		{Text: "DOOM CERTAIN SAYS PROFESSOR, he shouted, and his voice cracked in the middle of doom", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "noise"},
		{Text: "The extra edition had the odds printed in type two inches high", Kinds: tHigh, Reg: rPlain, Topic: "paper"},
		{Text: "He stopped shouting halfway down the street and just held the paper up over his head, and walked on like that, and people came out of the shops to read it as he passed and did not go back in", Kinds: tHigh, Reg: rPlain, Topic: "people"},
	}},
	{ages("victorian_age"), []skel{
		{Text: "His figures showed nothing, and he read them out anyway, all of them", Kinds: tNone, Reg: rJoke, Topic: "count"},
		{Text: "Repent or don't, he said, it hardly matters this year, and he got down off his crate", Kinds: tNone, Reg: rJoke, Form: fOverheard, Topic: "religion"},
		{Text: "The sandwich board said NOTHING MUCH, and a few people laughed", Kinds: tNone, Reg: rWry, Topic: "message"},
		{Text: "Mainly, he railed about drains", Kinds: tNoneLow, Reg: rWry, Form: fComplaint, Topic: "town"},
		{Text: "His table of figures showed a small risk, and he pointed at it with his umbrella every few minutes", Kinds: tLow, Reg: rWry, Topic: "count"},
		{Text: "A minor calamity, statistically speaking, he shouted, which drew a smaller crowd than doom usually does", Kinds: tLow, Reg: rWry, Form: fOverheard, Topic: "people"},
		{Text: "Figures in red ink", Kinds: tLowMed, Reg: rPlain, Topic: "paper"},
		{Text: "Rapping the board, he shouted “The odds are published, gentlemen, and they are against you”", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "noise"},
		{Text: "He had drawn the odds as a pie chart on the back of his sandwich board, and the slice for doom was large", Kinds: tMed, Reg: rWry, Topic: "paper"},
		{Text: "He took no pennies today", Kinds: tMedHigh, Reg: rPlain, Topic: "money"},
		{Text: "The figures do not lie, he roared, and the figures say the end, and at the front a woman fainted", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "people"},
		{Text: "He had turned the board round so the figures faced the crowd, and he said nothing at all", Kinds: tHigh, Reg: rPlain, Topic: "message"},
		{Text: "A police constable who had moved him along every week for a year stood beside him this time with his helmet under his arm and listened to the whole thing, and at the end left him where he was", Kinds: tHigh, Reg: rPlain, Topic: "authority"},
	}},
	{ages("electric_age"), []skel{
		{Text: "ALL QUIET STOP NOTHING TO REPORT STOP came over the wire from every station", Kinds: tNone, Reg: rPlain, Form: fNotice, Topic: "message"},
		{Text: "The dispatches were about the weather and a runaway horse", Kinds: tNone, Reg: rPlain, Topic: "animal"},
		{Text: "The operator read out the forecast odds and went back to his crossword", Kinds: tNone, Reg: rWry, Topic: "people"},
		{Text: "The wire carried the odds between a cattle report and a death notice", Kinds: tNoneLow, Reg: rPlain, Topic: "message"},
		{Text: "SLIGHT RISK STOP ADVISE CAUTION STOP, the dispatch read, and the postmaster pinned it in the window", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "paper"},
		{Text: "The odds came down the wire at noon and were chalked on the board outside the post office", Kinds: tLow, Reg: rPlain, Topic: "count"},
		{Text: "Dispatches from the south, nothing else", Kinds: tLowMed, Reg: rPlain, Form: fLedger, Topic: "count"},
		{Text: "RISK SUBSTANTIAL STOP PREPARE STOP ODDS FOLLOW STOP, and then the odds followed", Kinds: tMed, Reg: rWry, Form: fNotice, Topic: "message"},
		{Text: "The operator had been at the key for nine hours, and his wife had brought his dinner in a basin and taken it away again untouched, and still the dispatches kept coming from up the line", Kinds: tMed, Reg: rPlain, Topic: "work"},
		{Text: "Some stations up the line had stopped answering", Kinds: tMedHigh, Reg: rPlain, Topic: "machine"},
		{Text: "EVACUATE STOP EVACUATE STOP, the wire repeated, and the operator had to be relieved at his post", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "message"},
		{Text: "The odds came down the wire, and the operator read them and then sat back from the key", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
		{Text: "The last dispatch from the south ended in the middle of a word", Kinds: tHigh, Reg: rPlain, Topic: "message"},
	}},
	{ages("atomic_age"), []skel{
		{Text: "This is a test, said the announcer, this is only a test, and the programme came back", Kinds: tNone, Reg: rPlain, Form: fOverheard, Topic: "noise"},
		{Text: "The broadcast gave the odds as negligible and played a waltz", Kinds: tNone, Reg: rWry, Topic: "noise"},
		{Text: "The monthly siren test went off as scheduled, and nobody looked up", Kinds: tNone, Reg: rPlain, Topic: "noise"},
		{Text: "The announcer read the odds between the farm prices and the shipping forecast", Kinds: tNoneLow, Reg: rPlain, Topic: "count"},
		{Text: "Three times an hour the radio said “The civil defence authority advises that the risk remains low”", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "authority"},
		{Text: "The leaflet on what to do was reprinted and pushed through every letterbox", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "paper"},
		{Text: "Broadcasts every half hour now", Kinds: tLowMed, Reg: rPlain, Topic: "time"},
		{Text: "This is not a test, the announcer said, and then he read out the odds slowly, as if to children", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "noise"},
		{Text: "The radio gave the location of every public shelter in the district, one after another, for twenty minutes", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "building"},
		{Text: "Sirens, for a full minute", Kinds: tMedHigh, Reg: rPlain, Topic: "noise"},
		{Text: "Proceed to your designated shelter in an orderly fashion, said the announcer, and then said it again", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "authority"},
		{Text: "The broadcast gave the odds and then played the anthem", Kinds: tHigh, Reg: rPlain, Topic: "noise"},
		{Text: "The announcer's voice changed partway through the odds, and there was a pause long enough for people in kitchens all over the district to look up from what they were doing, and then he apologised, and went on", Kinds: tHigh, Reg: rPlain, Topic: "people"},
	}},
	{ages("modern_age"), []skel{
		{Text: "The story ran fourth, after a cat that had learned to use a lift", Kinds: tNone, Reg: rJoke, Topic: "animal"},
		{Text: "The anchor gave the odds with a smile and moved on to sport", Kinds: tNone, Reg: rPlain, Topic: "people"},
		{Text: "The on-screen graphic showed a probability so small it had to be zoomed in", Kinds: tNone, Reg: rWry, Topic: "machine"},
		{Text: "The expert in the studio called the risk manageable and was not invited back", Kinds: tNoneLow, Reg: rWry, Topic: "people"},
		{Text: "The graphic behind the anchor went from green to yellow halfway through the bulletin, and in thousands of living rooms people who had not been paying attention sat up and asked what they had missed", Kinds: tLow, Reg: rPlain, Topic: "machine"},
		{Text: "The risk is low but not zero, the anchor said, and held the look a moment longer than usual", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "people"},
		{Text: "They brought in a second expert to disagree with the first", Kinds: tLowMed, Reg: rWry, Topic: "argument"},
		{Text: "The anchor read the odds off the autocue, stopped, and read them again", Kinds: tMed, Reg: rPlain, Topic: "count"},
		{Text: "We go now to our correspondent outside the ministry, said the anchor, and the correspondent had nothing to add except the odds", Kinds: tMed, Reg: rWry, Form: fOverheard, Topic: "authority"},
		{Text: "No adverts tonight", Kinds: tMedHigh, Reg: rPlain, Topic: "machine"},
		{Text: "The anchor read the odds and then took off her glasses and sat for a moment without saying anything, live, in front of the whole country", Kinds: tHigh, Reg: rPlain, Topic: "people"},
		{Text: "Stay indoors, stay tuned, said the anchor, and the station logo disappeared from the corner of the screen", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "machine"},
		{Text: "The broadcast ran all night", Kinds: tHigh, Reg: rPlain, Topic: "time"},
	}},
	{ages("information_age"), []skel{
		{Text: "The chain email said, in bold, that there was nothing to worry about, and to forward it to ten people anyway", Kinds: tNone, Reg: rJoke, Topic: "message"},
		{Text: "The subject line read ALL CLEAR, and the attachment was a picture of a kitten", Kinds: tNone, Reg: rWry, Topic: "message"},
		{Text: "The odds were attached as a spreadsheet, and they were tiny", Kinds: tNone, Reg: rPlain, Topic: "count"},
		{Text: "Most people deleted it unread", Kinds: tNoneLow, Reg: rPlain, Topic: "message"},
		{Text: "It said the risk was small but real, and that ignoring it would bring seven years of bad luck", Kinds: tLow, Reg: rWry, Topic: "omen"},
		{Text: "The odds were in the email, in red, in a font nobody uses any more", Kinds: tLow, Reg: rWry, Topic: "count"},
		{Text: "It had been forwarded by people who never forward anything", Kinds: tLowMed, Reg: rPlain, Topic: "people"},
		{Text: "URGENT, PLEASE READ, said the subject line, and for once people did", Kinds: tMed, Reg: rWry, Form: fNotice, Topic: "message"},
		{Text: "The email gave the odds, cited a professor nobody could find, and ended with a prayer", Kinds: tMed, Reg: rWry, Topic: "religion"},
		{Text: "Your mother forwarded it", Kinds: tMedHigh, Reg: rPlain, Topic: "family"},
		{Text: "The subject line was just the odds, in capitals, and everybody who read it forwarded it before they had finished", Kinds: tHigh, Reg: rPlain, Topic: "message"},
		{Text: "It said to forward it to everyone you love, and people did, all of them, all at once, and somewhere around the fortieth forward the mail servers for half the country gave up and went dark", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
		{Text: "Nothing else in anybody's inbox", Kinds: tHigh, Reg: rPlain, Topic: "message"},
	}},
	{ages("digital_age"), []skel{
		{Text: "The video showed a man looking at a graph and shrugging, and it did well", Kinds: tNone, Reg: rJoke, Topic: "people"},
		{Text: "The top comment said the odds were lower than being hit by a vending machine", Kinds: tNone, Reg: rWry, Form: fOverheard, Topic: "count"},
		{Text: "It was a video about nothing, and it trended for an hour", Kinds: tNone, Reg: rWry, Topic: "rumour"},
		{Text: "The creator ended with a sponsor read", Kinds: tNoneLow, Reg: rWry, Topic: "money"},
		{Text: "The risk is low, like and subscribe, the video said, and then it ran an advert for a water filter", Kinds: tLow, Reg: rJoke, Form: fOverheard, Topic: "trade"},
		{Text: "The graph in the video showed a small bump, and the comments argued about the bump for days", Kinds: tLow, Reg: rWry, Topic: "argument"},
		{Text: "A thousand reuploads by noon", Kinds: tLowMed, Reg: rPlain, Topic: "count"},
		{Text: "The video walked through the odds with a whiteboard, and by the end the whiteboard was mostly red", Kinds: tMed, Reg: rPlain, Topic: "count"},
		{Text: "It was the first video in years that people watched all the way through without skipping, and when it ended most of them sat looking at the black screen before they did anything else", Kinds: tMed, Reg: rPlain, Topic: "people"},
		{Text: "The creator stopped smiling around minute four", Kinds: tMedHigh, Reg: rPlain, Topic: "people"},
		{Text: "The video was ninety seconds of a woman reading the odds into her phone and then saying goodbye to her children, who were off camera", Kinds: tHigh, Reg: rPlain, Topic: "family"},
		{Text: "The comments were turned off, and the like button, and the view count", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
		{Text: "Every site promoted it at once, which they never do", Kinds: tHigh, Reg: rWry, Topic: "rumour"},
	}},
	{ages("cyberpunk_age"), []skel{
		{Text: "The leaked memo said RISK NEGLIGIBLE, NO ACTION REQUIRED, and was signed by a vice president who had been dead for three years", Kinds: tNone, Reg: rWry, Form: fNotice, Topic: "paper"},
		{Text: "The ghost glitched through a memo about parking allocations and then vanished", Kinds: tNone, Reg: rJoke, Topic: "paper"},
		{Text: "The internal risk score was so low it rounded to zero, and the ghost seemed disappointed", Kinds: tNone, Reg: rWry, Topic: "count"},
		{Text: "The memo was mostly about budgets", Kinds: tNoneLow, Reg: rPlain, Topic: "money"},
		{Text: "The memo classified the risk as LOW, TOLERABLE, and the executives had initialled it without reading", Kinds: tLow, Reg: rWry, Form: fNotice, Topic: "authority"},
		{Text: "Probability of incident acceptable, repeat, acceptable, the ghost stuttered, and the lights flickered on the word acceptable", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "noise"},
		{Text: "The ghost leaked a revised model with the numbers circled", Kinds: tLowMed, Reg: rPlain, Topic: "paper"},
		{Text: "The leaked memo priced the catastrophe into the quarter and recommended executives relocate their families off-world", Kinds: tMed, Reg: rWry, Form: fNotice, Topic: "money"},
		{Text: "The board has been advised, the board has been advised, the board has, said the ghost, and cut out", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "authority"},
		{Text: "Security denied it immediately", Kinds: tMedHigh, Reg: rWry, Form: fNotice, Topic: "authority"},
		{Text: "The memo was titled CONTINGENCY FOR TOTAL LOSS and it had gone to the board a month ago", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "paper"},
		{Text: "The ghost read the internal odds aloud in a dead man's voice, and every screen in the arcology printed them as it spoke", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
		{Text: "Its last message was a list of the executives who had already left the city, with the times their private shuttles had cleared the towers, and the list was long, and some of the times were a week old", Kinds: tHigh, Reg: rPlain, Topic: "name"},
	}},
	{ages("fusion_age"), []skel{
		{Text: "Containment nominal, said the warden, all systems within tolerance, and it went back to monitoring", Kinds: tNone, Reg: rPlain, Form: fOverheard, Topic: "machine"},
		{Text: "The fault tree came back green", Kinds: tNone, Reg: rPlain, Topic: "machine"},
		{Text: "The warden published its failure probability, which was lower than the chance of the building being struck by a meteorite", Kinds: tNone, Reg: rWry, Topic: "count"},
		{Text: "The warden recommended a routine inspection, as it does every week", Kinds: tNoneLow, Reg: rPlain, Form: fNotice, Topic: "machine"},
		{Text: "The warden reported a minor anomaly in the plasma ring, probability of breach low, and kept monitoring", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "machine"},
		{Text: "The failure estimate went up by a fraction, and the warden recommended nobody panic", Kinds: tLow, Reg: rWry, Topic: "count"},
		{Text: "The warden began running the containment checks hourly instead of daily", Kinds: tLowMed, Reg: rPlain, Topic: "time"},
		{Text: "On every deck the warden said “Probability of containment failure is elevated, recommend nonessential staff withdraw”", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "authority"},
		{Text: "The warden published the full fault tree, which it has never done before", Kinds: tMed, Reg: rPlain, Topic: "paper"},
		{Text: "The warden stopped using the word nominal", Kinds: tMedHigh, Reg: rWry, Topic: "machine"},
		{Text: "In the voice it uses for fire drills the warden said “Containment failure probable, this is not a drill”", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "noise"},
		{Text: "The warden locked the control room from the inside and began venting plasma to space without consulting anybody", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
		{Text: "The warden's failure estimate was the largest number anyone had seen on those screens, and the senior engineer, who had written half the warden's code herself, read it three times and then went to find her children", Kinds: tHigh, Reg: rPlain, Topic: "count"},
	}},
	{ages("space_age"), []skel{
		{Text: "PRIORITY LOW, NO THREAT DETECTED, the monitor reported, as it has every day for forty years", Kinds: tNone, Reg: rPlain, Form: fNotice, Topic: "message"},
		{Text: "The station tracked the object for a full day, through two shift changes and one argument about coffee, and then reclassified it as a lump of dirty ice going nowhere in particular, and went back to watching its patch of sky", Kinds: tNone, Reg: rPlain, Topic: "machine"},
		{Text: "The estimate matched background noise", Kinds: tNone, Reg: rPlain, Topic: "count"},
		{Text: "The packet was mostly calibration readings", Kinds: tNoneLow, Reg: rPlain, Form: fLedger, Topic: "machine"},
		{Text: "OBJECT ON INTERCEPT, PROBABILITY LOW, CONTINUING TO TRACK, the monitor reported, and went on tracking", Kinds: tLow, Reg: rPlain, Form: fNotice, Topic: "machine"},
		{Text: "The monitoring station raised its estimate by a hair and asked for more antenna time", Kinds: tLow, Reg: rPlain, Topic: "machine"},
		{Text: "Only updates now", Kinds: tLowMed, Reg: rPlain, Topic: "message"},
		{Text: "The monitor's probability of impact was high enough that the duty officer woke the commander instead of logging it", Kinds: tMed, Reg: rPlain, Topic: "people"},
		{Text: "UPDATE, PROBABILITY INCREASING, the packets said, one every ten minutes", Kinds: tMed, Reg: rPlain, Form: fNotice, Topic: "time"},
		{Text: "The station requested permission to wake its reserve crew", Kinds: tMedHigh, Reg: rPlain, Form: fNotice, Topic: "people"},
		{Text: "IMPACT PROBABLE, IMPACT PROBABLE, the monitor sent, and then the coordinates, over and over", Kinds: tHigh, Reg: rPlain, Form: fNotice, Topic: "message"},
		{Text: "The monitor's last packet gave the odds to four decimal places and a time of arrival", Kinds: tHigh, Reg: rPlain, Topic: "count"},
		{Text: "The station on the far side of the moon had begun, without being told, to move its own orbit away", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
	}},
	{ages("interstellar_age"), []skel{
		{Text: "The beacon's loop had changed, for the first time in eighty years, to say that the sky over the dead colony was clear", Kinds: tNone, Reg: rPlain, Topic: "message"},
		{Text: "The beacon played its usual message and nothing new", Kinds: tNone, Reg: rPlain, Topic: "noise"},
		{Text: "Analysis of the loop found no threat, only the dead", Kinds: tNone, Reg: rPlain, Topic: "casualty"},
		{Text: "The beacon repeated its old warning, which was eighty years out of date", Kinds: tNoneLow, Reg: rWry, Topic: "time"},
		{Text: "A new line had been added to the beacon's loop, a man's voice saying the risk was small and they should not worry", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "noise"},
		{Text: "The beacon's risk estimate, still computed by the colony's last working machine, had ticked up", Kinds: tLow, Reg: rPlain, Topic: "machine"},
		{Text: "The dead colony's instruments had started reporting again", Kinds: tLowMed, Reg: rPlain, Topic: "machine"},
		{Text: "In the voice of a child reading a prepared statement the beacon said “Whatever happened to us is coming your way”", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "Somehow the colony's last working machine, which should have run out of power decades ago, had worked out the odds for a settlement it had never heard of and was transmitting them, patiently, on a loop, to whoever might be listening", Kinds: tMed, Reg: rPlain, Topic: "count"},
		{Text: "The loop ended in names", Kinds: tMedHigh, Reg: rPlain, Topic: "name"},
		{Text: "Do not come here, do not stay there, it is moving, the beacon said, and then the loop started again from the beginning", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "The estimate on the beacon matched the one it had broadcast the week the colony died", Kinds: tHigh, Reg: rPlain, Topic: "count"},
		{Text: "The beacon stopped", Kinds: tHigh, Reg: rPlain, Topic: "noise"},
	}},
	{ages("galactic_age"), []skel{
		{Text: "The relay's message, rendered into words, said roughly that nothing was coming and that it was sorry to have woken anyone", Kinds: tNone, Reg: rWry, Topic: "message"},
		{Text: "The relay hummed for a day and then fell silent, apparently satisfied", Kinds: tNone, Reg: rPlain, Topic: "noise"},
		{Text: "The geometry resolved into a shape the linguists called reassurance", Kinds: tNone, Reg: rPlain, Topic: "message"},
		{Text: "The relay's estimate was small, and it seemed to find the whole matter beneath it", Kinds: tNoneLow, Reg: rWry, Topic: "count"},
		{Text: "A small ending approaches a small people, the relay said, which the linguists thought was meant kindly", Kinds: tLow, Reg: rWry, Form: fOverheard, Topic: "message"},
		{Text: "The relay drew the odds as a spiral with one short dark arm", Kinds: tLow, Reg: rPlain, Topic: "omen"},
		{Text: "The repetitions grew closer together", Kinds: tLowMed, Reg: rPlain, Topic: "time"},
		{Text: "The relay said that what came for the builders comes for you, and showed the builders' last city, in the geometry, as a hole", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "omen"},
		{Text: "The relay's probability, once converted, was higher than the linguists wanted to say out loud", Kinds: tMed, Reg: rPlain, Topic: "count"},
		{Text: "The relay's hum dropped an octave", Kinds: tMedHigh, Reg: rPlain, Topic: "noise"},
		{Text: "We said this to others before you, the relay said, and then there was no one left to say it to", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "The relay showed the odds as a closed shape, and the linguists could find no way into it", Kinds: tHigh, Reg: rPlain, Topic: "omen"},
		{Text: "Every relay in the galaxy, including several nobody had known were relays, began transmitting one identical geometry at once, and the linguists who had spent their lives on the differences between them had nothing left to study", Kinds: tHigh, Reg: rPlain, Topic: "machine"},
	}},
	{ages("quantum_age"), []skel{
		{Text: "Relax, your future self said, nothing happens, go to bed", Kinds: tNone, Reg: rWry, Form: fOverheard, Topic: "sleep"},
		{Text: "The message from the future was mostly an apology for a haircut", Kinds: tNone, Reg: rJoke, Topic: "message"},
		{Text: "Your future self gave the odds, rolled their eyes, and signed off", Kinds: tNone, Reg: rWry, Topic: "count"},
		{Text: "The message said you would worry about this for nothing, and that you always do", Kinds: tNoneLow, Reg: rWry, Topic: "message"},
		{Text: "It's probably fine, said the message in your own voice, but I'd check", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "The odds your future self sent were small, and came with a note saying they had been wrong before", Kinds: tLow, Reg: rWry, Topic: "count"},
		{Text: "The message kept breaking off and starting again from the beginning, the sender interrupted by something the message never names", Kinds: tLowMed, Reg: rPlain, Topic: "message"},
		{Text: "From nine years out you said “I've seen this go both ways, and I'm keeping which way it went for me to myself”", Kinds: tMed, Reg: rWry, Form: fOverheard, Topic: "time"},
		{Text: "Your future self sent the odds and a list of things to move to the lower levels, in your handwriting, in the order you would have thought of them, with the one you always forget underlined three times", Kinds: tMed, Reg: rPlain, Form: fLedger, Topic: "haul"},
		{Text: "Your own voice sounded frightened", Kinds: tMedHigh, Reg: rPlain, Topic: "noise"},
		{Text: "Don't do what I did, said the message, and then your own voice read out the odds, and then your name, as if you might not be listening", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "name"},
		{Text: "Your name and the odds, nothing more", Kinds: tHigh, Reg: rPlain, Topic: "name"},
		{Text: "It ended in the middle of a sentence, and the timestamp on it was tomorrow", Kinds: tHigh, Reg: rPlain, Topic: "time"},
	}},
	{ages("transcendent_age"), []skel{
		{Text: "The one of you who did not make it studied this branch end to end and said it could not see its own ending here", Kinds: tNone, Reg: rPlain, Topic: "omen"},
		{Text: "Wrong branch, it said, and seemed almost disappointed", Kinds: tNone, Reg: rWry, Form: fOverheard, Topic: "stranger"},
		{Text: "Your unmade self found nothing in this timeline that matched its own", Kinds: tNone, Reg: rPlain, Topic: "time"},
		{Text: "Branches like this one go on", Kinds: tNoneLow, Reg: rPlain, Topic: "time"},
		{Text: "It said that a few versions of you had ended here", Kinds: tLow, Reg: rPlain, Form: fOverheard, Topic: "casualty"},
		{Text: "It showed you a version of this week in which things went only slightly wrong, and then took the version away", Kinds: tLow, Reg: rPlain, Topic: "omen"},
		{Text: "It kept glancing behind you", Kinds: tLowMed, Reg: rPlain, Topic: "stranger"},
		{Text: "This is where I stopped, it said, and it stood in the exact place, and the air there was colder", Kinds: tMed, Reg: rPlain, Form: fOverheard, Topic: "weather"},
		{Text: "It gave the odds as the share of your branches that did not continue, and the share was large", Kinds: tMed, Reg: rPlain, Topic: "count"},
		{Text: "Its face kept changing into yours", Kinds: tMedHigh, Reg: rPlain, Topic: "stranger"},
		{Text: "This is the one, it said, this is the one I came from, and it would not stop saying it until it faded", Kinds: tHigh, Reg: rPlain, Form: fOverheard, Topic: "message"},
		{Text: "It showed you the ending it had lived through, the whole of it, slowly, the way you would show someone the house you grew up in, and you have not been able to stop seeing it since", Kinds: tHigh, Reg: rPlain, Topic: "omen"},
		{Text: "It gave the odds, and you realised they were your odds, and that it had heard them once too", Kinds: tHigh, Reg: rPlain, Topic: "count"},
	}},
}
