package flavor

// ExpeditionFailure — a party was sent out and it went badly.
//
// The log line directly above this one already says "<Name> failed! Partial loot
// recovered." So none of the sentences here say that it failed, and none of them
// weigh the loss against the recovery. They say who did not come home, what broke,
// who is being blamed, what the map got wrong, and what the families were told.
// See catalog.go for the rules, and catalog_exp_success.go for the voice.
//
// Grim is not the same as melodramatic, and this file leans on the flat register
// harder than the others do. The strongest line available here is usually a plain
// account of what somebody did with their hands the following morning.

// --- slot banks --------------------------------------------------------------
//
// Noun phrases, lowercase, one tight category per bank, no era-coded nouns —
// both banks are drawn by ungated sentences, so both must land in every age.

var expFailBanks = map[string][]string{
	// A carried thing that did not come home. Definite noun phrases, so the frame
	// supplies only the verb.
	"exp_fail_kit": {
		"the spare rope", "the good boots", "the maps", "the spare gloves",
		"the big cook pot", "the second pack", "the drinking water", "the heavy axe",
		"the spare boots", "the first-aid kit", "the climbing line", "the long knife",
		"the folded bedding", "the last dry clothes", "the signal mirror",
		"the digging tools", "the spare water", "the last of the food",
	},
	// An injury, named the way a room names one: by the part of the body everyone
	// is trying not to look at.
	"exp_fail_wound": {
		"the bad hand", "the wrapped ribs", "the split lip", "the swollen knee",
		"the burnt forearm", "the shoulder that will not lift",
		"the eye that has not opened", "the cut under the jaw", "the leg that drags",
		"the bandaged foot", "the arm in the sling", "the broken wrist",
		"the gash across the back", "the ankle nobody will look at",
		"the two missing fingers", "the hand that will not close",
		"the bite on the calf", "the tooth that came out on the way",
	},
}

// --- the sentences -----------------------------------------------------------

// expFailTemplates is the ExpeditionFailure skeleton set: one ungated pool that
// lands in any age, plus one pool per era bucket for the imagery that does not
// travel.
func expFailTemplates() []tmpl {
	out := pool("exp_fail_any", erasAny, expFailAny)
	out = append(out, pool("exp_fail_grounded", erasGrounded, expFailGrounded)...)
	out = append(out, pool("exp_fail_late", erasLate, expFailLate)...)
	out = append(out, pool("exp_fail_ancient", erasAncient, expFailAncient)...)
	out = append(out, pool("exp_fail_feudal", erasFeudal, expFailFeudal)...)
	out = append(out, pool("exp_fail_industrial", erasIndustrial, expFailIndustrial)...)
	out = append(out, pool("exp_fail_digital", erasDigital, expFailDigital)...)
	out = append(out, pool("exp_fail_cosmic", erasCosmic, expFailCosmic)...)
	return out
}

// expFailAny fires in every age, so nothing in it may name an era-coded object.
// Counting, arguing, burying, waiting at a door and blaming the quiet one are
// timeless; carts, sidings and airlocks are not.
var expFailAny = []skel{
	// --- short ---
	{Text: "Seven back of nine", Reg: rPlain, Form: fLedger, Topic: "casualty"},
	{Text: "The first-aid kit is gone", Reg: rPlain, Topic: "kit"},
	{Text: "Nobody has eaten", Reg: rPlain, Topic: "food"},
	{Text: "Both stretchers came in full", Reg: rPlain, Topic: "wound"},
	{Text: "It took nineteen days", Reg: rPlain, Topic: "time"},
	{Text: "Kel has stopped talking", Reg: rPlain, Topic: "name"},
	{Text: "The water was bad", Reg: rPlain, Topic: "food"},
	{Text: "One boot came home", Reg: rWry, Form: fLedger, Topic: "kit"},
	{Text: "There will be a hearing", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "Somebody's mother is at the door", Reg: rPlain, Topic: "town"},
	{Text: "The wounded were carried in at the back", Reg: rPlain, Topic: "wound"},
	{Text: "Serit has said her piece", Reg: rPlain, Topic: "name"},
	{Text: "The light went early", Reg: rPlain, Topic: "weather"},
	{Text: "Everyone is eating standing up", Reg: rPlain, Topic: "people"},
	{Text: "The news got home a day before they did", Reg: rPlain, Topic: "message"},
	{Text: "Blame is going round", Reg: rWry, Form: fOverheard, Topic: "argument"},
	{Text: "Nothing was found out there", Reg: rPlain, Topic: "map"},

	// --- mid ---
	{Text: "Two names have been scratched off the list and left unreplaced", Reg: rPlain, Form: fLedger, Topic: "casualty"},
	{Text: "Nine went out and the man carried in makes seven", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "The youngest of them has been sitting outside since they got in", Reg: rPlain, Topic: "people"},
	{Text: "Somebody has taken the boots off the dead and it was the right call", Reg: rWry, Topic: "kit"},
	{Text: "Somebody traded ~ for directions that turned out to be wrong", Slot: "exp_fail_kit", Reg: rWry, Topic: "trade"},
	{Text: "Whoever was carrying ~ has not been asked about it yet", Slot: "exp_fail_kit", Reg: rPlain, Topic: "argument"},
	{Text: "Nobody wants to look too long at ~", Slot: "exp_fail_wound", Reg: rPlain, Topic: "wound"},
	{Text: "The dressing on ~ has been changed four times today", Slot: "exp_fail_wound", Reg: rPlain, Topic: "wound"},
	{Text: "There is an argument about who should have carried ~", Slot: "exp_fail_kit", Reg: rWry, Topic: "argument"},
	{Text: "A child keeps asking about ~ and keeps being sent out", Slot: "exp_fail_wound", Reg: rPlain, Topic: "town"},
	{Text: "The marks on the far side stop halfway and start again nowhere", Reg: rPlain, Topic: "map"},
	{Text: "Whoever drew the last stretch of the map has not come forward", Reg: rWry, Topic: "map"},
	{Text: "The route back was longer than the route out by three days", Reg: rPlain, Topic: "ground"},
	{Text: "The food ran out on the eighth day and the water on the ninth", Reg: rPlain, Form: fLedger, Topic: "food"},
	{Text: "They ate what they had and then they ate what they had left", Reg: rWry, Topic: "food"},
	{Text: "A man in the back room will not have his boots taken off", Reg: rPlain, Topic: "wound"},
	{Text: "The one who wanted to turn back on the fourth day is being careful not to mention it", Reg: rWry, Topic: "argument"},
	{Text: "Two of them have already asked to be sent out again", Reg: rWry, Topic: "people"},
	{Text: "A boy has been sent round the doors with the names", Reg: rPlain, Form: fNotice, Topic: "message"},
	{Text: "Nobody has been able to say where the third one went", Reg: rPlain, Topic: "casualty"},
	{Text: "The count of what came home was done once and left at that", Reg: rWry, Form: fLedger, Topic: "count"},
	{Text: "What came back has been put in the small room and locked in", Reg: rPlain, Topic: "haul"},
	{Text: "Somebody is being blamed and it is the quietest of them", Reg: rWry, Topic: "argument"},
	{Text: "The story is being told badly and by the wrong people", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "There is an account going round that has them braver and taller", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "A door has been shut on the far side of the house all evening", Reg: rPlain, Topic: "building"},
	{Text: "Two of them came in without their packs and would not say where", Reg: rPlain, Topic: "haul"},
	{Text: "The ground out there is worse than anybody was told", Reg: rPlain, Form: fComplaint, Topic: "ground"},
	{Text: "Whoever gave them the directions has left the district", Reg: rWry, Topic: "stranger"},
	{Text: "The ones who managed to sleep have said they would rather have stayed awake", Reg: rPlain, Topic: "sleep"},
	{Text: "A man walked in behind them who has not been asked his business", Reg: rPlain, Topic: "stranger"},
	{Text: "The one who was supposed to be watching has been left alone about it", Reg: rPlain, Topic: "argument"},
	{Text: "Something in the packs smells and nobody is naming it", Reg: rPlain, Topic: "smell"},
	{Text: "The second count came to the same bad number as the first", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "Half the town heard before the other half and it went badly", Reg: rWry, Topic: "rumour"},
	{Text: "An animal got into the food stores on the fifth night", Reg: rPlain, Topic: "animal"},
	{Text: "Two of them are already telling it as though they were elsewhere", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "The last of the light was spent looking for one man", Reg: rPlain, Topic: "casualty"},

	{Text: "Somebody has been sent back out for ~ and has not been told to hurry", Slot: "exp_fail_kit", Reg: rWry, Topic: "kit"},
	{Text: "A price has been put on ~ by somebody who was not there", Slot: "exp_fail_kit", Reg: rWry, Form: fLedger, Topic: "money"},
	{Text: "The woman doing the bandaging looked at ~ and sent for her sister", Slot: "exp_fail_wound", Reg: rPlain, Topic: "people"},
	{Text: "Two people have given different accounts of how they came by ~", Slot: "exp_fail_wound", Reg: rPlain, Form: fOverheard, Topic: "rumour"},

	// --- long ---
	{Text: "The names were read out once in the morning by a man who got two of them wrong, and there has been an argument about that since which is easier to have than the other one", Reg: rWry, Form: fNotice, Topic: "casualty"},
	{Text: "Somebody has been round every door in the row already, which was kindly meant and has arrived a good deal faster than the truth of it", Reg: rPlain, Topic: "town"},
	{Text: "Serit came in last, walked past everybody without stopping, and has been sitting with the youngest one's kit in her lap since the middle of the afternoon", Reg: rPlain, Topic: "name"},
	{Text: "There is a boy of about nine standing at the corner watching the door, and every time he is sent home he comes back by a different street", Reg: rPlain, Topic: "town"},
	{Text: "What is left has been laid out on the floor and is being written down by somebody who keeps having to stop and start the line again", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "Two of them have given accounts of the same afternoon that agree about the weather and about nothing else at all", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "The order to turn back was given a full day after the point at which everybody now says it should have been given, and the man who gave it has said as much himself", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "The count of what came home is nine items on a list of forty, and the man reading the list aloud stopped at about the twentieth", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "The blame has settled on the youngest for now, on the grounds that he is the youngest, and two people who were there have said so out loud and been ignored", Reg: rWry, Topic: "argument"},
	{Text: "There is a swelling on one of them that was described as nothing on the fourth day, as manageable on the seventh, and is now being looked at by three people at once", Reg: rPlain, Topic: "wound"},
	{Text: "Somebody has written the names on the wall by the door in a hand that gets steadily worse toward the bottom of the list", Reg: rPlain, Topic: "paper"},
	{Text: "There was food waiting for twelve and seven came in, and the woman who cooked it has been standing over the rest of it for an hour without touching it", Reg: rPlain, Topic: "food"},
	{Text: "The route was argued over before they left, in front of witnesses, and everybody who argued for it has spent the evening explaining that they argued for it conditionally", Reg: rWry, Topic: "argument"},
	{Text: "Two of them will not go into the back room where the others are, and have been standing in the passage for long enough that somebody has brought them chairs", Reg: rPlain, Topic: "building"},

	// --- very long ---
	{Text: "The list of what went out runs to two full sides and the list of what came home fits comfortably on the back of the second, and the man who wrote both of them has left them on the table and gone outside", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "A decision was made on the fifth day that everybody agreed with at the time, that two of them now say they never agreed with, and that the man who made it cannot be asked about, being one of the ones still out there", Reg: rWry, Topic: "argument"},
	{Text: "A woman has been sitting on the step since the afternoon with a bag of her son's clothes in her lap, and whoever tells her is going to have to sit down beside her to do it", Reg: rPlain, Topic: "town"},
	{Text: "What came home fits in one small room and has been counted, written down, counted again by somebody who did not trust the first count, and written down a second time on the same sheet in a different hand", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "There is a man sitting by the door who has been asked four times whether he wants anything to eat, has said no four times, and is now being brought something anyway by a woman who has stopped asking", Reg: rPlain, Topic: "food"},
	{Text: "Two accounts of the last afternoon have now been given, one by a man who was there for all of it and one by a man who was there for the first hour, and it is the second account that has gone round the town", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "The eldest of them has been out at the wall since they got in, doing a job that did not need doing, and three people have gone out to fetch him in and all three have come back alone and said he is busy", Reg: rPlain, Topic: "people"},

	// --- kind: scouting ---
	{Text: "Four days out, turned on the fifth", Kinds: []string{"scouting"}, Reg: rPlain, Form: fLedger, Topic: "time"},
	{Text: "The far side was never reached and will have to be tried again", Kinds: []string{"scouting"}, Reg: rPlain, Topic: "map"},
	{Text: "The sketch stops in the middle of a line", Kinds: []string{"scouting"}, Reg: rPlain, Topic: "paper"},

	// --- kind: military ---
	{Text: "The fighting went on longer than the food", Kinds: []string{"military"}, Reg: rPlain, Topic: "weapon"},
	{Text: "Four wounded and one dead", Kinds: []string{"military"}, Reg: rPlain, Form: fLedger, Topic: "casualty"},
	{Text: "Whoever they met was better at it and knew the ground", Kinds: []string{"military"}, Reg: rPlain, Topic: "border"},
	{Text: "The order was to take the place and hold it, and they took it at about noon and held it until roughly the middle of the night, and the second half of that has been left out of most of the tellings", Kinds: []string{"military"}, Reg: rWry, Form: fOverheard, Topic: "rumour"},

	// --- tone ---
	{Text: "The dead have not been counted aloud yet", Tones: []Tone{Grim}, Reg: rPlain, Topic: "casualty"},
	{Text: "The list on the wall is being read by people who cannot read", Tones: []Tone{Grim}, Reg: rPlain, Topic: "town"},
	{Text: "There are more empty places at the table than full ones", Tones: []Tone{Grim}, Reg: rPlain, Topic: "food"},
	{Text: "The two by the wall have been left where they were put, under a sheet, and everybody coming through the room has slowed down at the same point on the floor and then walked on", Tones: []Tone{Grim}, Reg: rPlain, Topic: "casualty"},
	{Text: "Everyone who stayed home has an excellent theory", Tones: []Tone{Wry}, Reg: rJoke, Form: fOverheard, Topic: "rumour"},
	{Text: "The plan is being called ambitious by the man who wrote it", Tones: []Tone{Wry}, Reg: rJoke, Topic: "argument"},
	{Text: "A great many people have remembered this evening that they had reservations at the time, and between them they have produced more reservations than there were people in the room when it was decided", Tones: []Tone{Wry}, Reg: rJoke, Form: fOverheard, Topic: "argument"},
	{Text: "There is already a list of whose fault it was, in order", Tones: []Tone{Wry}, Reg: rJoke, Topic: "argument"},

	// --- the order title, in a frame a verb-led name survives ---
	{Text: "A page marked {subject} has been turned face down", Needs: needSubject, Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "Whoever wrote the {subject} order is not in the room", Needs: needSubject, Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "Somebody stopped reading at the line that reads {subject}", Needs: needSubject, Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "Nothing filed under {subject} came home the way it left", Needs: needSubject, Reg: rPlain, Form: fNotice, Topic: "haul"},
	{Text: "The board still shows the {subject} order as out", Needs: needSubject, Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "Two men refused the {subject} order before it went out, were noted down as having refused it, and have spent the evening being avoided by people who would rather not talk to them just now", Needs: needSubject, Reg: rWry, Form: fNotice, Topic: "argument"},
	{Text: "The whole file marked {subject} has been put back in the box it came out of, and the box has gone up on the high shelf, and somebody has written the date on the lid", Needs: needSubject, Reg: rPlain, Form: fNotice, Topic: "paper"},

	// --- the resource, as a thing in a room ---
	{Text: "Whatever came back of the {res} fits in one hand", Needs: needRes, Reg: rPlain, Topic: "haul"},
	{Text: "What is left of the {res} has gone into one box", Needs: needRes, Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "There is too little {res} here to argue over", Needs: needRes, Reg: rPlain, Topic: "money"},
	{Text: "Nobody has been put on the {res} tonight, and nobody has asked why", Needs: needRes, Reg: rPlain, Topic: "money"},
	{Text: "Whatever came home of the {res} was set down in the middle of the floor by the first man through the door, and it has not been moved since, and people have been walking round it all evening", Needs: needRes, Reg: rPlain, Topic: "building"},
	{Text: "They set down {res_haul} and nobody moved to help", Needs: needRes | needMassRes, Reg: rPlain, Topic: "haul"},
	{Text: "Nothing has been done with {res_stores} since the count", Needs: needRes | needMassRes, Reg: rPlain, Topic: "money"},
	{Text: "All of it together came to {amt_res}", Needs: needRes | needAmount, Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "The figure written up is {amt_res}, and the man who wrote it has been asked whether that is the whole of it, and said yes without looking up", Needs: needRes | needAmount, Reg: rPlain, Form: fLedger, Topic: "count"},
}

// expFailGrounded is the part of the old ungated pool whose imagery is a town
// with lanes, dogs and a washing line: true from the Stone Age to the
// Modern Age, and wrong on a station. Moved here after a corpus review.
var expFailGrounded = []skel{
	{Text: "The dog is missing", Reg: rPlain, Topic: "animal"},
	{Text: "The wounded were laid out along the wall in the order they came in rather than the order anybody would have chosen, so the two worst are at the far end where the draught is, and moving them has been discussed all evening", Reg: rPlain, Topic: "wound"},
	{Text: "The dog that went out with them came back on its own two days ahead, and everybody understood what that meant, and it was fed and nobody said so", Reg: rPlain, Topic: "animal"},
	{Text: "Two graves were dug and neither has a marker yet", Reg: rPlain, Form: fLedger, Topic: "casualty"},
	{Text: "The washing has been done twice and some of it has been burnt", Reg: rPlain, Topic: "smell"},
	{Text: "The wind took the shelter apart at about the worst hour", Reg: rPlain, Topic: "weather"},
	{Text: "Nobody has taken the blankets off the two by the wall", Reg: rPlain, Topic: "casualty"},
	{Text: "The wounded were brought in on planks cut from the shelter, which is why nobody slept dry for the last four nights, and which nobody has complained about", Reg: rPlain, Topic: "wound"},
	{Text: "The one who kept the days went on marking them right to the end, so there is a stick with fourteen notches on it in a pack that came home with somebody else", Reg: rPlain, Topic: "time"},
	{Text: "The animals that went out with them came back without their loads, arriving in ones and twos over most of a day, and one of them has still not turned up", Reg: rPlain, Topic: "animal"},
	{Text: "A woman came in from the outer houses with bread and left it on the step without knocking, and it has been sitting there since because bringing it in would mean opening the door", Reg: rPlain, Topic: "food"},
	{Text: "A woman has been at the door since first light and will be told soon", Reg: rPlain, Topic: "town"},
	{Text: "Somebody in the outer houses has been telling people all evening that he said from the start it would go this way, and four separate people have now told him to his face that he said the opposite in front of them", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "The council will meet about it on the day after next, which gives everybody two clear days to arrive at the same account of events", Tones: []Tone{Wry}, Reg: rJoke, Form: fNotice, Topic: "authority"},
	{Text: "The families were told before the council was, which is being looked into", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The good lamp went over at the crossing along with the man holding it, and the lamp has been mentioned rather more often this evening than the man", Reg: rWry, Topic: "kit"},
	{Text: "The order was read to them before they went, and the paper it was written on came home in a wet pack with the ink gone, and it has been laid out flat to dry on the table with a weight on each corner", Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "The salt is ruined", Reg: rPlain, Topic: "food"},
	{Text: "They held the ground for a night and gave it back at dawn", Kinds: []string{"military"}, Reg: rPlain, Topic: "weapon"},
	{Text: "They walked back with {amt_res} and a man on a plank", Needs: needRes | needAmount, Reg: rPlain, Topic: "wound"},
	{Text: "Word went round the outer houses first, then the middle ones, and reached the family last, which is how it always goes and is always described afterwards as unfortunate", Reg: rPlain, Form: fComplaint, Topic: "rumour"},
	{Text: "A name was cut into the rock at the last camp and left there", Reg: rPlain, Topic: "name"},
	{Text: "The last camp was made in a bad place because the good place was an hour further on and nobody had an hour left in them", Reg: rPlain, Topic: "ground"},
	{Text: "The light out on the ridge was seen from home and taken for something else", Reg: rPlain, Topic: "border"},
	{Text: "The man who mapped the crossing has been asked to come and explain it, has agreed to come, and has now sent word that he is unwell", Reg: rWry, Topic: "map"},
	{Text: "The river took ~ on the second morning", Slot: "exp_fail_kit", Reg: rPlain, Topic: "ground"},
	{Text: "They walked away from ~ at the second camp and never went back", Slot: "exp_fail_kit", Reg: rPlain, Topic: "kit"},
	{Text: "Two went ahead to look at the crossing and one came back to describe it, and the description is the only thing anybody has to work from", Kinds: []string{"scouting"}, Reg: rPlain, Topic: "map"},
	{Text: "Whatever is out past the tree line stayed out past it", Kinds: []string{"scouting"}, Reg: rPlain, Topic: "map"},
	{Text: "A stranger walked with them for two days on the way back, shared what he had, took nothing, and turned off before they were close enough to be seen from home", Reg: rPlain, Topic: "stranger"},
	{Text: "The best of the water was found the day after they turned back", Reg: rJoke, Topic: "ground"},
	{Text: "The country past the water was never seen properly because the weather sat on it for four days and then they had no days left to spend", Kinds: []string{"scouting"}, Reg: rPlain, Topic: "weather"},
	{Text: "The map got the water wrong and everything after it followed", Reg: rPlain, Topic: "map"},
	{Text: "The water they were counting on turned out to be a day further along than the marks said, which was survivable, and the water after that turned out not to be there at all, which was the part that did the damage", Reg: rPlain, Topic: "map"},
	{Text: "They turned back at the water because it was up, waited two days for it to drop, and it dropped on the third, by which time the food was already a problem", Reg: rPlain, Topic: "ground"},
	{Text: "They walked the last stretch in silence and have kept it up", Reg: rPlain, Topic: "people"},
	{Text: "What went into the water with ~ has been listed out on a sheet and pinned up by the door, and people keep stopping to read it on their way past", Slot: "exp_fail_kit", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "Everything that could be carried was carried, everything that could be dragged was dragged, and a good deal of it was put down again within sight of home", Reg: rPlain, Topic: "haul"},
	{Text: "Rain for six days", Reg: rPlain, Topic: "weather"},
	{Text: "The blades came home dull and nobody is cleaning them tonight", Kinds: []string{"military"}, Reg: rPlain, Topic: "weapon"},
	{Text: "The pack that came home heaviest turned out to hold one man's whole share of the water, carried nine days after the man himself had stopped needing it", Reg: rPlain, Topic: "haul"},
	{Text: "The weather turned on the sixth night and stayed turned, and everything after that in every account anybody has given begins with a note about the cold", Reg: rPlain, Topic: "weather"},
	{Text: "Three packs, one man", Reg: rPlain, Form: fLedger, Topic: "haul"},
}

// expFailLate is the digital and cosmic voice: the field notes have become
// logs, and the logs have started to notice how long everything takes.
var expFailLate = []skel{
	{Text: "The mission clock is still running because the person authorised to stop it is one of the people on the mission", Reg: rWry, Topic: "time"},
	{Text: "The tracking board has three lights left on it", Reg: rPlain, Form: fLedger, Topic: "message"},
	{Text: "The families were sent an automated message before anyone could stop it, and a person has been assigned to call each of them and apologise for the tone", Reg: rWry, Topic: "message"},
	{Text: "Everything they were carrying is still transmitting its position, and the positions have stayed the same for four days", Reg: rPlain, Topic: "kit"},
	{Text: "Their names are still on the duty roster for next week", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "A memorial has been scheduled", Reg: rPlain, Form: fNotice, Topic: "religion"},
	{Text: "The review board would like it understood that the loss was within projected tolerances, and has asked for the projection to be sent to the families so that they can understand it too", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The stretchers were not needed", Reg: rPlain, Topic: "casualty"},
	{Text: "The countdown was never reset", Reg: rPlain, Topic: "time"},
	{Text: "Six launched, two recovered", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "Their lockers have been sealed", Reg: rPlain, Topic: "casualty"},
	{Text: "All leave is cancelled", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The last message was routine", Reg: rPlain, Topic: "message"},
	{Text: "The tracking screen is blank", Reg: rPlain, Topic: "machine"},
	{Text: "Kel is still at his desk", Reg: rPlain, Topic: "people"},
	{Text: "Next of kin have been notified", Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "Legal got here first", Reg: rWry, Form: fComplaint, Topic: "authority"},
	{Text: "One helmet was recovered", Reg: rPlain, Topic: "kit"},
	{Text: "The car park is still full", Reg: rPlain, Topic: "building"},
	{Text: "Serit asked to be alone", Reg: rPlain, Topic: "people"},
	{Text: "The comms log ends mid-word", Reg: rPlain, Topic: "message"},
	{Text: "The press are in the car park", Reg: rWry, Topic: "money"},
	{Text: "The injuries are mostly burns", Reg: rPlain, Topic: "wound"},
	{Text: "The alarms are still going", Reg: rPlain, Topic: "noise"},
	{Text: "A review has been ordered", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "Their names are still on the door", Reg: rPlain, Topic: "name"},
	{Text: "Nine signals, then four", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "Lunch was left on the desks", Reg: rPlain, Topic: "food"},
	{Text: "The last position they sent is still on the main screen, and it has been left there", Reg: rPlain, Topic: "machine"},
	{Text: "The mission plan has been printed out and is being read by people who signed it without reading it", Reg: rWry, Topic: "paper"},
	{Text: "The families were given a room with a view of the landing area", Reg: rPlain, Topic: "people"},
	{Text: "Their suit telemetry stops one after another over about a minute", Reg: rPlain, Topic: "machine"},
	{Text: "A recorded message from one of them arrived an hour after the others stopped transmitting", Reg: rPlain, Topic: "message"},
	{Text: "The press office has three statements ready and is waiting to be told which is true", Reg: rWry, Topic: "authority"},
	{Text: "The recovered helmet went to the lab with its visor still down", Reg: rPlain, Topic: "kit"},
	{Text: "Everyone who approved the launch window is reading the weather report again", Reg: rWry, Topic: "argument"},
	{Text: "One of the survivors keeps asking about the others by their first names", Reg: rPlain, Topic: "people"},
	{Text: "The medics worked on the two who came back until the morning shift arrived and then kept going", Reg: rPlain, Topic: "wound"},
	{Text: "The risk assessment for this mission put the chance of this at one in several hundred", Reg: rWry, Topic: "paper"},
	{Text: "A second search was authorised and then called off before it launched", Reg: rPlain, Topic: "casualty"},
	{Text: "Accounts has already sent round a form about the lost equipment", Reg: rWry, Form: fComplaint, Topic: "money"},
	{Text: "The clocks in the operations room are still set to mission time", Reg: rPlain, Topic: "time"},
	{Text: "A cleaner came in at the usual hour, saw the room, and went away again", Reg: rPlain, Topic: "people"},
	{Text: "Their spare suits are still hanging in the prep room, labelled with their names", Reg: rPlain, Topic: "kit"},
	{Text: "The simulation they trained on has been run again with the new numbers, and it ends the same way", Reg: rWry, Topic: "machine"},
	{Text: "A condolence message has been drafted and is waiting on a signature from someone who is asleep", Reg: rPlain, Topic: "message"},
	{Text: "Two of the survivors are in the same room and have not spoken to each other", Reg: rPlain, Topic: "people"},
	{Text: "The rumour on the floor is that the route was chosen by a spreadsheet", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "The recovery team brought back what they could and wrote a short list of what they could not", Reg: rPlain, Topic: "casualty"},
	{Text: "The mission commander has cleared her calendar for the week and her office door is shut", Reg: rWry, Topic: "authority"},
	{Text: "The survivors were sedated on arrival and are expected to sleep until tomorrow afternoon", Reg: rPlain, Topic: "sleep"},
	{Text: "The search grid on the wall has been widened three times since the morning", Reg: rPlain, Topic: "map"},
	{Text: "The automated systems kept logging normal readings for an hour after it was over", Reg: rWry, Topic: "machine"},
	{Text: "A child's drawing is taped to the inside of one of the empty lockers", Reg: rPlain, Topic: "people"},
	{Text: "Counselling is available on the third floor from nine", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "The incident report has a field for cause, and the field is blank", Reg: rWry, Form: fLedger, Topic: "paper"},
	{Text: "The pilot who flew them out has asked to speak to the families herself", Reg: rPlain, Topic: "people"},
	{Text: "One of the survivors came back wearing someone else's jacket and will not take it off", Reg: rPlain, Topic: "kit"},
	{Text: "The system sent them all an automated reminder about their annual training this morning", Reg: rWry, Topic: "machine"},
	{Text: "The call signs have been retired", Reg: rPlain, Topic: "name"},
	{Text: "The search team went back over the site three more times than it was ordered to, because the team lead kept finding reasons to look again", Reg: rPlain, Topic: "casualty"},
	{Text: "The inquiry panel has been chosen from people who had nothing to do with the mission, which has meant bringing in two people who had never heard of it", Reg: rWry, Topic: "authority"},
	{Text: "The families arrived before the official notification did, because one of them works in the building and saw the screens on the way to lunch", Reg: rPlain, Topic: "people"},
	{Text: "The last voice recording is two minutes of routine checks followed by a pause, and the pause has been listened to more than anything else on it", Reg: rPlain, Topic: "message"},
	{Text: "The summary for the board has been started by three different people, and each of them stopped at the second paragraph", Reg: rWry, Topic: "paper"},
	{Text: "One of the two who made it back has injuries the medical team had only read about, and they have been on a call with specialists since midnight", Reg: rPlain, Topic: "wound"},
	{Text: "The equipment that failed passed every test it was given, and the engineers have spent the day writing a test it would not have passed", Reg: rWry, Topic: "machine"},
	{Text: "The survivors were debriefed separately and gave the same account, except for one detail about the order things happened in, which has been set aside for later", Reg: rPlain, Topic: "people"},
	{Text: "Their personal effects are being boxed up by the people who sat nearest to them, because nobody else knows which mug belonged to whom", Reg: rPlain, Topic: "casualty"},
	{Text: "A senior official flew in to address the staff, spoke for four minutes, and left before anyone could ask him anything", Reg: rWry, Topic: "authority"},
	{Text: "The status board still shows the mission as active, with a timer counting up from the moment contact was lost", Reg: rPlain, Topic: "time"},
	{Text: "The mission planning software is offering to schedule a follow-up, and the prompt has been sitting on the screen all day", Reg: rJoke, Topic: "machine"},
	{Text: "The youngest of the dead had been on the team for a month, and most of the people in the building knew her only by sight", Reg: rPlain, Topic: "people"},
	{Text: "The engineers blame the procedure and the planners blame the engineers, and the procedure was written by the two of them together", Reg: rWry, Topic: "argument"},
	{Text: "A message from one of the dead arrived this morning on a delay, cheerful and ordinary, about a problem with the heating in her quarters", Reg: rPlain, Topic: "message"},
	{Text: "Most of what they took with them is still out there, logged and tagged and transmitting, and there is no plan yet to go back for any of it", Reg: rPlain, Topic: "kit"},
	{Text: "All staff have been asked not to discuss the mission on personal accounts, and the request has been posted on every official account the organisation runs", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "A man from the families' liaison office has been in the building since the morning and has yet to find the right room", Reg: rPlain, Topic: "people"},
	{Text: "The recovery team found them where the tracking said they would be and brought back everything they could carry, and the team lead has written a report in the plainest language anyone here has ever read and wants it sent up unedited", Reg: rPlain, Topic: "casualty"},
	{Text: "The organisation's statement describes the loss as a tragedy and promises a full review, and it was approved within an hour, which is faster than anything else this organisation has approved in living memory", Reg: rWry, Topic: "authority"},
	{Text: "One of the survivors has been sitting in the corridor outside the medical unit since she was discharged, and the staff have stopped asking her to move and started bringing her tea, and she has drunk every cup without looking up", Reg: rPlain, Topic: "people"},
	{Text: "The failure analysis has traced the problem to a component flagged for replacement in a maintenance report two years ago, and the report has been found, and the name at the bottom of it belongs to one of the people who did not come back", Reg: rWry, Topic: "machine"},
	{Text: "The families were told to expect news within the hour, and then within the next hour, and by the evening the liaison officer had stopped giving times and was simply sitting with them, which they understood before she said anything", Reg: rPlain, Topic: "time"},
	{Text: "Every document connected to the mission has been locked for the inquiry, including the menu for the celebration dinner booked for the night they were due back, which a junior assistant is now having to explain to the restaurant", Reg: rWry, Topic: "paper"},
	{Text: "The last thing received from the team was a request for a weather update, sent in the normal format with the normal sign-off, and the reply is still sitting in the outbox with no one left to deliver it to", Reg: rPlain, Topic: "message"},
	{Text: "The spare parts were not enough", Reg: rPlain, Topic: "kit"},
	{Text: "The emergency beacon never fired", Reg: rPlain, Topic: "message"},
	{Text: "Flights are grounded pending review", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The team leader's husband is in reception", Reg: rPlain, Topic: "people"},
	{Text: "The failure warning arrived on everyone's phone about ten minutes after it stopped being useful", Reg: rWry, Topic: "machine"},
	{Text: "The flight recorders have been recovered and are being flown to the lab in a sealed case", Reg: rPlain, Topic: "time"},
	{Text: "The mission's own website still has a countdown on it, counting to a return that has been and gone", Reg: rWry, Topic: "paper"},
	{Text: "The survivors were given fresh clothes and one of them asked for her old ones back", Reg: rPlain, Topic: "people"},
	{Text: "The equipment losses have been totalled and the number has been sent upstairs with no comment", Reg: rWry, Form: fLedger, Topic: "count"},
	{Text: "The families were offered rooms in a hotel nearby and most of them have stayed in the building instead", Reg: rPlain, Topic: "sleep"},
}

// expFailAncient — fires, herds, hides, spears, the elders.
var expFailAncient = []skel{
	{Text: "Every spear they took is still out there", Reg: rPlain, Form: fLedger, Topic: "weapon"},
	{Text: "The store-pit is half empty and it is not yet midwinter", Reg: rWry, Topic: "food"},
	{Text: "The hides came home ruined", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "The elders have not spoken", Reg: rWry, Topic: "authority"},
	{Text: "The drums were beaten slow at dusk", Reg: rPlain, Topic: "noise"},
	{Text: "The ford ran higher than anyone remembered and took two of them", Reg: rPlain, Topic: "ground"},
	{Text: "An arrow came out of the trees and nobody saw the hand", Reg: rPlain, Topic: "border"},
	{Text: "The herd was lost on the second night and never found again", Reg: rPlain, Topic: "animal"},
	{Text: "A hide was left over the two of them where they fell", Reg: rPlain, Topic: "casualty"},
	{Text: "The watch-fire was not lit on the night it mattered", Reg: rPlain, Form: fComplaint, Topic: "border"},
	{Text: "They came back along the low ground because the ridge was watched", Reg: rPlain, Topic: "ground"},
	{Text: "The elders have asked for the names and the spears, in that order", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "There is a hut standing empty at the end of the row", Reg: rPlain, Topic: "building"},
	{Text: "The spring on the far side turned out to be dry, which two of them had said it would be before they set out and have not repeated since", Reg: rWry, Topic: "map"},
	{Text: "The old man who read the ridge for them read it wrong, and he knows it, and he has been sitting outside his own doorway since the middle of the afternoon", Reg: rPlain, Topic: "name"},
	{Text: "A boy carried a spear the whole way out and dropped it in the water on the way back, and has been telling everybody about the water rather than the spear", Reg: rWry, Topic: "weapon"},
	{Text: "The drums stopped early and have not started again, and the man who beats them says he will start again when there is something to beat them for", Reg: rPlain, Topic: "noise"},
	{Text: "Two hides came home and one of them is over a man who cannot be moved yet, so the count of hides is being given as one by anybody who is asked", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "Smoke went up on the ridge behind them for two days running and nobody has explained whose it was", Reg: rPlain, Topic: "border"},
	{Text: "The harvest was left standing while everybody watched the low ground, and it is still standing, and somebody will have to say something about it tomorrow", Reg: rPlain, Form: fComplaint, Topic: "town"},
	{Text: "They buried one where he fell because the ground was soft there and it was not soft anywhere else for most of a day in either direction", Reg: rPlain, Topic: "casualty"},
	{Text: "The elders have called everybody to the fire at first light, which has been taken by most people to mean the same thing, and by two people to mean something worse", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "A spear was left planted at the place they turned back from, which somebody did on purpose and nobody has criticised", Reg: rPlain, Topic: "weapon"},
	{Text: "The valley they were told to cross turned out to hold water most of the way across it, which the man who told them about it has now been reminded of by four separate people", Reg: rWry, Topic: "map"},
}

// expFailFeudal — carts, gates, bells, clerks, stewards, musters.
var expFailFeudal = []skel{
	{Text: "One cart came back", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "The bells were not rung", Reg: rWry, Topic: "noise"},
	{Text: "The muster roll has been read and put away", Reg: rWry, Form: fLedger, Topic: "casualty"},
	{Text: "Two banners came home wet", Reg: rPlain, Topic: "kit"},
	{Text: "The steward has gone to bed early", Reg: rWry, Topic: "authority"},
	{Text: "The gate was opened for them without the horn being blown", Reg: rPlain, Topic: "border"},
	{Text: "The ford took a cart and everything that was on it", Reg: rPlain, Topic: "ground"},
	{Text: "A rider went out to meet them and came back at a walk", Reg: rPlain, Topic: "message"},
	{Text: "The clerks have written it all down and put it away", Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "Supper was laid for the whole company and half of it is untouched", Reg: rPlain, Topic: "food"},
	{Text: "A herald was sent ahead with better news than turned out to be true", Reg: rWry, Form: fNotice, Topic: "message"},
	{Text: "The village heard the wagons before it heard anything else", Reg: rPlain, Topic: "town"},
	{Text: "The undercroft has room in it that nobody wanted to have", Reg: rWry, Topic: "building"},
	{Text: "The pickets on the wall saw them at first light and rang nothing, and there has been a good deal of discussion since about whether that was a kindness", Reg: rPlain, Topic: "border"},
	{Text: "The steward has had the muster roll on his table since noon with a candle beside it and has not yet drawn a line through anything", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "Wax has been spilled across the fair copy, which the clerk noticed an hour later, and the whole of it is being written out again by lamplight", Reg: rPlain, Form: fComplaint, Topic: "paper"},
	{Text: "A cart was left at the crossing with a wheel off and its load in the water, and two men have gone out with rope to see what can be had back", Reg: rPlain, Topic: "haul"},
	{Text: "The village priest has been at three doors already this evening and has two more to do before he can go home", Reg: rPlain, Topic: "religion"},
	{Text: "The militia turned out at the gate to bring them in and stood there a long while, and by the time the last of them was through the line had thinned out to about six", Reg: rPlain, Topic: "town"},
	{Text: "Somebody rang the bells at the wrong hour out of habit, realised halfway through, and stopped, which was worse than either finishing or not starting", Reg: rWry, Topic: "noise"},
	{Text: "The road past the ford is cut again and the long way round adds two days, which is being explained to the steward by a man who has explained it before", Reg: rWry, Form: fComplaint, Topic: "ground"},
	{Text: "A banner came home in a state that means it will have to be replaced rather than mended, and the woman who made the first one has offered to make the second", Reg: rPlain, Topic: "kit"},
	{Text: "The quartermaster has the count and will not give it out until the steward has had it, which is correct and is making him unpopular in the yard", Reg: rWry, Form: fNotice, Topic: "count"},
	{Text: "Two riders have been sent back out along the road with lamps to look for anybody still walking, and they were told to turn round at midnight and have not", Reg: rPlain, Topic: "casualty"},
}

// expFailIndustrial — depots, sidings, foremen, telegrams, triplicate.
var expFailIndustrial = []skel{
	{Text: "The telegram was short", Reg: rWry, Form: fNotice, Topic: "message"},
	{Text: "The return freight weighed almost nothing", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "The payroll will be adjusted", Reg: rWry, Form: fNotice, Topic: "money"},
	{Text: "The freight book has gone home in the foreman's coat", Reg: rWry, Form: fLedger, Topic: "paper"},
	{Text: "The depot was kept open", Reg: rWry, Topic: "building"},
	{Text: "The foreman signed for what came back and went outside", Reg: rPlain, Form: fNotice, Topic: "authority"},
	{Text: "Freight came in on the late train with two men riding on it", Reg: rPlain, Topic: "haul"},
	{Text: "The warehouse book has a page torn out of the middle", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "A wire went out at four and was answered at half past nine", Reg: rPlain, Form: fNotice, Topic: "message"},
	{Text: "The office telephone has been ringing since the news reached town", Reg: rPlain, Topic: "message"},
	{Text: "It has been written up in triplicate and filed in a hurry", Reg: rJoke, Form: fNotice, Topic: "paper"},
	{Text: "The lorries came in one behind the other with their lamps still lit", Reg: rPlain, Topic: "machine"},
	{Text: "The night shift stayed on without being asked", Reg: rPlain, Topic: "people"},
	{Text: "The company will hear a version of this that has been through three offices, and by the time it gets there the weather in it will be considerably worse", Reg: rWry, Form: fNotice, Topic: "rumour"},
	{Text: "There is a wire on the desk that came in this afternoon and has been left where it landed, and two people have picked it up and put it down again unopened", Reg: rPlain, Form: fNotice, Topic: "message"},
	{Text: "The platform was cleared for the eleven o'clock and the eleven o'clock came in with the lamps down, which everybody standing on it understood before the doors opened", Reg: rPlain, Topic: "message"},
	{Text: "The foreman's tally and the office tally agree for once, which has been remarked on by two men who have not thought it through", Reg: rWry, Form: fLedger, Topic: "count"},
	{Text: "A crate that came back has been opened, gone through, closed again and put in the annexe, and nobody has been able to say what was supposed to be in it", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "The men who came off the train were told to go home and paid for the full week, and about half of them went to the yard instead and have been there since", Reg: rPlain, Topic: "people"},
	{Text: "The siding has been kept clear all evening for a second train that was mentioned once in a garbled wire and that nobody has since been able to confirm", Reg: rPlain, Form: fComplaint, Topic: "machine"},
	{Text: "A photograph was taken at the platform when they went out, three weeks ago, by a man from the town paper, and somebody has taken it down off the office wall", Reg: rPlain, Topic: "town"},
	{Text: "The depot clock stopped at some point in the afternoon and nobody has wound it, and the whole building has been working off a pocket watch on the counter", Reg: rPlain, Topic: "time"},
	{Text: "The shareholders' letter is due on Friday and the man who writes it has been sitting with a blank sheet since six, and has twice asked what the weather was like out there", Reg: rWry, Form: fNotice, Topic: "paper"},
	{Text: "Two of them came in on stretchers and one walked off his at the platform, and the doctor has written that down in a way that makes clear what he thinks of it", Reg: rWry, Topic: "wound"},
}

// expFailDigital — uplinks, drones, feeds, analysts, channels.
var expFailDigital = []skel{
	{Text: "The uplink dropped twice", Reg: rPlain, Topic: "machine"},
	{Text: "Most of the telemetry is from one drone", Reg: rPlain, Form: fLedger, Topic: "machine"},
	{Text: "The channel is open and nobody is on it", Reg: rWry, Topic: "noise"},
	{Text: "Nobody has left the building", Reg: rWry, Topic: "sleep"},
	{Text: "The feed ran out at twenty past six", Reg: rPlain, Topic: "machine"},
	{Text: "The after-action report has been started four times", Reg: rJoke, Form: fNotice, Topic: "paper"},
	{Text: "An analyst has watched the same nine seconds all afternoon", Reg: rPlain, Topic: "people"},
	{Text: "The network held perfectly and carried every bit of it home", Reg: rWry, Topic: "machine"},
	{Text: "The channel was closed at four, and people went back to their desks without sitting down", Reg: rPlain, Topic: "noise"},
	{Text: "A badge has been left on a desk that its owner will not want back", Reg: rPlain, Topic: "casualty"},
	{Text: "The uplink logs have been pulled and sent upstairs", Reg: rPlain, Form: fNotice, Topic: "paper"},
	{Text: "A drone came back on one rotor and landed on the pad by itself", Reg: rPlain, Topic: "machine"},
	{Text: "The feed cut at the point everybody has since wanted to see", Reg: rPlain, Topic: "machine"},
	{Text: "Two analysts have gone through the last hour of it frame by frame and have come out of the room with the same account, which is the first thing all evening that anybody has been able to rely on", Reg: rPlain, Topic: "paper"},
	{Text: "The channel logs from the second team stop mid-sentence, and the sentence they stop in the middle of has been read aloud once and has not been read aloud again", Reg: rPlain, Form: fOverheard, Topic: "message"},
	{Text: "A junior analyst flagged the ground conditions four days ago in a note that went to three people, and one of the three has spent this evening finding out which of the other two read it", Reg: rWry, Form: fNotice, Topic: "argument"},
	{Text: "The after-action briefing has been put back to the morning because the man who has to give it has been on the floor since before it happened and cannot yet be got to stop working", Reg: rPlain, Form: fNotice, Topic: "sleep"},
	{Text: "There is a drone still out there somewhere on its last power, sending the same position every forty seconds, and the room has stopped pretending it is going to move", Reg: rPlain, Topic: "machine"},
	{Text: "The coffee has been going since about four and there is a cup on every desk on the floor, and most of them are cold, and none of them have been thrown out", Reg: rPlain, Topic: "food"},
	{Text: "Someone patched a drone with tape three weeks ago and it is one of the two that came home, and the engineer who did it has not said anything about it and is not going to", Reg: rWry, Topic: "machine"},
	{Text: "The feed from the lead element is being replayed on the wall screen for the fourth time, and the room has rearranged its chairs so that fewer people are facing it", Reg: rPlain, Topic: "people"},
	{Text: "A note has gone round the floor asking people to keep the channel clear, and three people have replied to everyone to say they will", Reg: rPlain, Form: fNotice, Topic: "message"},
	{Text: "The network flagged the whole thing as routine at the time and is still flagging it as routine now, and somebody has been given the job of going in and changing that", Reg: rWry, Form: fNotice, Topic: "paper"},
	{Text: "Two people who were not on the operation have been on the floor since the middle of the evening asking what happened, and they have been answered politely, and they are still asking", Reg: rWry, Form: fOverheard, Topic: "rumour"},
	{Text: "Three drones never checked in", Reg: rPlain, Topic: "machine"},
	{Text: "The hashtag started before the announcement", Reg: rWry, Topic: "rumour"},
	{Text: "Their phones go to voicemail", Reg: rPlain, Topic: "message"},
	{Text: "Two feeds live, four dark", Reg: rPlain, Form: fLedger, Topic: "count"},
	{Text: "Social media is suspended for staff", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The last frame of the feed is a ceiling", Reg: rPlain, Topic: "machine"},
	{Text: "An analyst is crying in the stairwell and her supervisor is standing beside her pretending to read something", Reg: rPlain, Topic: "people"},
	{Text: "The network logged the outage as scheduled maintenance, and the person who scheduled it has been asked to come in", Reg: rWry, Topic: "machine"},
	{Text: "Their implants are still pinging a location nobody can reach", Reg: rPlain, Topic: "machine"},
	{Text: "A video of the last minute is already circulating, and it is the wrong video", Reg: rWry, Topic: "rumour"},
	{Text: "The group chat still has their messages at the bottom of it", Reg: rPlain, Topic: "message"},
	{Text: "The after-action template has a box for lessons learned and the box has been left empty on purpose", Reg: rWry, Topic: "paper"},
	{Text: "The analyst who planned the route has been sent home and keeps logging back in", Reg: rPlain, Topic: "people"},
	{Text: "The client wants to know whether the deadline still stands", Reg: rWry, Topic: "money"},
	{Text: "A drone was sent back for them and came home with pictures that have been shown to four people and locked away", Reg: rPlain, Topic: "machine"},
	{Text: "The smart building dimmed the operations room at the usual hour, and the staff have been working in the half-dark since because the override needs a code only the facilities manager has", Reg: rJoke, Topic: "machine"},
	{Text: "A phone keeps ringing in the prep room, and the caller is a family member who has not been told yet", Reg: rPlain, Topic: "message"},
	{Text: "The feed was cut from the public stream within seconds, and the decision to cut it has been praised and criticised in roughly equal amounts", Reg: rWry, Topic: "authority"},
	{Text: "The medical drone reached the site first and sent back what it found, and the analyst who received it asked to be replaced at her console", Reg: rPlain, Topic: "casualty"},
	{Text: "Every system involved reported green right up until they all went down together, and the vendor has sent a representative who has so far offered a brochure", Reg: rJoke, Topic: "machine"},
	{Text: "The operations floor emptied at the end of the shift except for four people who stayed at their consoles watching feeds that showed nothing at all", Reg: rPlain, Topic: "people"},
	{Text: "The fusion plant's safety report cleared the route a week ago, and the engineer who signed it has asked to see the report again with the lights on", Reg: rWry, Topic: "paper"},
	{Text: "One of them posted a photograph from the field an hour before contact was lost, a picture of his boots with a view behind them, and it has been shared several hundred thousand times since", Reg: rPlain, Topic: "message"},
	{Text: "A crisis team was assembled in the conference room and spent its first hour trying to get the video link to work", Reg: rWry, Topic: "authority"},
	{Text: "The cyber team is still inside the target system, holding a door open for people who are not coming back through it", Reg: rPlain, Topic: "machine"},
}

// expFailCosmic — hulls, bays, relays, transponders, airlocks.
var expFailCosmic = []skel{
	{Text: "The hull is opened along one seam", Reg: rPlain, Topic: "machine"},
	{Text: "Bay two came home empty", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "The relay heard nothing", Reg: rWry, Topic: "message"},
	{Text: "Three suits came back", Reg: rPlain, Form: fLedger, Topic: "kit"},
	{Text: "The airlock has been cycling", Reg: rWry, Topic: "machine"},
	{Text: "They came in on emergency air with the reactor down", Reg: rPlain, Topic: "machine"},
	{Text: "The transponder was answering right up to the last hour", Reg: rWry, Topic: "message"},
	{Text: "A repair patch let go on the way in and took a panel with it", Reg: rPlain, Topic: "machine"},
	{Text: "The dock crew came out and then stopped where they were", Reg: rPlain, Topic: "town"},
	{Text: "The manifest has more on it than the bay does", Reg: rWry, Form: fLedger, Topic: "count"},
	{Text: "Vacuum got into the forward compartment on the second day", Reg: rPlain, Topic: "casualty"},
	{Text: "Two names have been added to the plate by the lock", Reg: rPlain, Topic: "name"},
	{Text: "Orbital watch logged the approach and did not ask for a count", Reg: rPlain, Form: fNotice, Topic: "border"},
	{Text: "The relay picked up a carrier on the third day with nothing on it, held it for two hours, lost it, and has been listening on the same frequency since without being told to", Reg: rPlain, Topic: "message"},
	{Text: "The bay doors were opened before the ship was properly down because everybody on the deck could already see how many suits were standing up inside", Reg: rPlain, Topic: "machine"},
	{Text: "A freighter crew answered the distress and got there six hours after it went out, which was as fast as anybody could have done it and is being said out loud a good deal this evening", Reg: rPlain, Topic: "stranger"},
	{Text: "The reactor was run past every limit on the way home and it held, and the engineer who ran it that way has been sitting in the corridor outside the bay since they docked", Reg: rPlain, Topic: "machine"},
	{Text: "There is a boot in the cargo net that has been in the cargo net since the unload, and the dock crew have worked round it all evening", Reg: rPlain, Topic: "kit"},
	{Text: "The hull sensors have been reporting the same fault every ninety seconds since they came in, and somebody has muted the panel rather than answer it", Reg: rWry, Topic: "machine"},
	{Text: "The manifest was signed at the far end by a man whose name is on the other list as well, and the two lists have been put side by side on the counter and left there", Reg: rPlain, Form: fLedger, Topic: "paper"},
	{Text: "Two of the crew have not come out of the suits yet and have been sitting in them in the bay for most of an hour, and the medical officer has decided to let that run", Reg: rPlain, Topic: "people"},
	{Text: "Everything in the forward bay is scorched down one side and the smell has got into the corridor, and the door at the end of it has been shut and taped", Reg: rPlain, Topic: "smell"},
	{Text: "The dock lights were left burning for the whole of the last watch and were still burning when they came in, which the officer who ordered it has been thanked for by three people", Reg: rPlain, Topic: "town"},
	{Text: "A crate came home sealed, with a number on it that matches nothing on either bay list, and it has been put in the corner of the office and nobody has opened it", Reg: rPlain, Form: fLedger, Topic: "haul"},
	{Text: "Their suits are still in orbit", Reg: rPlain, Topic: "casualty"},
	{Text: "Light-lag means they died last month", Reg: rWry, Topic: "time"},
	{Text: "The next of kin are on the shuttle up", Reg: rPlain, Topic: "people"},
	{Text: "The distress call is still arriving", Reg: rPlain, Topic: "message"},
	{Text: "Their quarters are sealed and the neighbours are watering the plants", Reg: rWry, Form: fNotice, Topic: "authority"},
	{Text: "The ship's mind has stopped answering questions about the last day", Reg: rPlain, Topic: "machine"},
	{Text: "The restored copies of the crew remember leaving and nothing after it, and they are being kept away from the news with great care", Reg: rWry, Topic: "people"},
	{Text: "Their signal will keep arriving for years", Reg: rPlain, Topic: "time"},
	{Text: "The dock crew recovered one of the pods intact and have left it sealed", Reg: rPlain, Topic: "casualty"},
	{Text: "There is a legal question about whether the crew who died and the crew being restored from backup are owed the same pension, and it has gone to the lawyers", Reg: rWry, Topic: "authority"},
	{Text: "The wreck is drifting out of the system at a speed that means no one now alive will see it recovered", Reg: rPlain, Topic: "map"},
	{Text: "The relay kept forwarding their automated status reports for three days, each one reporting all systems nominal", Reg: rPlain, Topic: "message"},
	{Text: "By the time the news reached the families on the inner stations, two of the families had moved away and one had forgotten there was a mission", Reg: rWry, Topic: "time"},
	{Text: "One survivor has asked to be put back in cold sleep until the inquiry is over", Reg: rPlain, Topic: "people"},
	{Text: "The hull was found empty", Reg: rPlain, Topic: "casualty"},
	{Text: "The navigation system has calculated the most likely place they ended up, and the answer is a star", Reg: rWry, Topic: "machine"},
	{Text: "The cargo bay was jettisoned on the way down to save the ship, and everything they went for went with it", Reg: rPlain, Topic: "haul"},
	{Text: "The freighter crew who found them would rather not be named, and have put in for leave", Reg: rPlain, Topic: "people"},
	{Text: "The station chaplain has asked what the procedure is for a crew that might still be alive in a different reference frame", Reg: rWry, Topic: "religion"},
	{Text: "On the station the funeral has been held, and on the ship, if the ship is anywhere, it is still the same afternoon", Reg: rPlain, Topic: "time"},
	{Text: "The reactor telemetry shows a controlled shutdown, done by the book, a few minutes after the last voice contact", Reg: rPlain, Topic: "machine"},
	{Text: "The inquiry will report its findings in a century or so, when the last of the signal arrives, and the chair has been chosen for her patience", Reg: rWry, Topic: "authority"},
	{Text: "The airlock was cycled for them on schedule and then again an hour later, by a dock officer who says he did it by mistake", Reg: rPlain, Topic: "people"},
	{Text: "The ship's name has been retired for a thousand years, which is the rule, and which nobody here will live to see lifted", Reg: rWry, Topic: "name"},
	{Text: "Something answered the distress call before the rescue ship did, and what it said has been classified above the level of anyone who can read it", Reg: rWry, Topic: "stranger"},
}
